[package]
name = "ntrumls"
version = "0.9.6"
links = "ntrumls"
build = "build.rs"
license = "GPL-3.0+"
readme = "README.md"
repository = "https://github.com/FractalGlobal/NTRUMLS-rs"
documentation = "https://docs.rs/ntrumls/"
authors = ["Razican <iban@fractal.global>"]
description = """
NTRUMLS library for Rust. An interface to the reference implementation.
"""
keywords = ["NTRUMLS", "NTRU", "NTRUSign", "NTRUEncrypt"]
exclude = ["src/c/doc/*", "src/c/ntrumls/*", "src/c/ntrumls-vs.VC.db"]

[dependencies]
cty = { git = "https://github.com/japaric/cty.git" }

[build-dependencies]
gcc = "^0.3"

[dev-dependencies]
rand = "^0.3"
